version: "3.8"
services:

  

  go:
    container_name: go
    image: vineeshajasti/golang-api:api_V_1.0
    build:
      context: .
      dockerfile: Dockerfile
 
    restart: always
    ports:
      - "5002:5002"
    volumes:
      - .:/app/

  node_n:
    build: ./Server-UI
    image: vineeshajasti/ui:react
    container_name: node_n
    
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    networks:
      - default
    restart: always
