version: "3.8"
services:

  postgres:
    build: 
      context: ./database          
    container_name: postgres
    image: vineeshajasti/postgres_v_01:postgres_V_1.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: smp
    ports:
      - "5432:5432"  
    networks:
      - default

  go:
    container_name: go
    image: vineeshajasti/golang-api:api_V_1.0
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "postgres"
    restart: always
    ports:
      - "5002:5002"
    volumes:
      - .:/app/

  node_n:
    build: ./Server-UI
    image: vineeshajasti/ui:react
    container_name: node_n
    
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    networks:
      - default
    restart: always