export const inputFormElements = [
  {
    name: "creator",
    type: "text",
    placeholder: " cretor name",
    label: "creator Name",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "ctreated_date",
    label: "created date",
    type: "date",
    // placeholder: "date",

    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "End date",
    type: "date",
    placeholder: "End date",
    label: "End date",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "Manufacturer",
    type: "text",
    placeholder: "Manufacturer",
    label: "Manufacturer",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "Numer of server",
    type: "number",
    placeholder: "Numer of server",
    label: "Numer of server",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "CPU Model",
    placeholder: "CPU Model",
    label: "CPU Model ",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "CPU Sockets",
    type: "number",
    placeholder: "CPU Sockets",
    label: "CPU Sockets ",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "DIMM Size",
    placeholder: "DIMM Size",
    label: "DIMM Size ",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "DIMM Quantity",
    type: "number",
    placeholder: "DIMM Quantity",
    label: "DIMM Quantity ",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "OS Vender",
    placeholder: "OS Vender",
    label: "OS Vender",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "OS Controller",
    placeholder: "OS Controller",
    label: "OS Controller",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "OS Capacity",
    placeholder: "OS Capacity",
    label: "OS Capacity",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "Disk Vender",
    placeholder: "Disk Vender",
    label: "Disk Vender",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "Disk Controller",
    placeholder: "Disk Controller",
    label: "Disk Controller",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "Disk Capacity",
    placeholder: "Disk Capacity",
    label: "Disk Capacity",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "Network Type",
    placeholder: "Network Type",
    label: "Network Type",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "Network Speed",
    placeholder: "Network Speed",
    label: "Network Speed",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "Network Port",
    type: "select",
    placeholder: "Network Port",
    label: "Network Port",
    options: [
      {
        value: "UK",
        displayValue: "United kingdom",
      },
      {
        value: "IN",
        displayValue: "India",
      },
    ],
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "Special switcging needs",
    placeholder: "Special switcging needs",
    label: "Special switcging needs",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 12,
  },
  {
    name: "email",
    type: "email",
    placeholder: "Enter email",
    label: "Email",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 20,
    sm: 6,
  },
  {
    name: "phone",
    type: "number",
    placeholder: "Enter phone number",
    label: "Phone",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "street",
    placeholder: "Enter street",
    label: "Street",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "city",
    placeholder: "Enter city name",
    label: "City",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "state",
    placeholder: "Enter state",
    label: "State",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "country",
    placeholder: "Enter country name",
    label: "Country",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "pincode",
    placeholder: "Enter pincode number",
    label: "Pincode",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 12,
  },
];
